# Generated by Django 2.1.5 on 2019-02-19 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWS_link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('small_poster_url', models.CharField(default='https://filmie-storage.s3.eu-central-1.amazonaws.com/movie-posters/w175/', max_length=255)),
                ('medium_poster_url', models.CharField(default='https://filmie-storage.s3.eu-central-1.amazonaws.com/movie-posters/w300/', max_length=255)),
                ('original_poster_url', models.CharField(default='https://filmie-storage.s3.eu-central-1.amazonaws.com/movie-posters/original/', max_length=255)),
                ('list_cover_url', models.CharField(default='https://filmie-storage.s3.eu-central-1.amazonaws.com/list-covers/', max_length=255)),
                ('profile_picture_url', models.CharField(default='https://filmie-storage.s3.eu-central-1.amazonaws.com/profiles/', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('movies', models.ManyToManyField(to='api.Movies')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
